import React from 'react';
import { Provider } from 'react-redux';
import { createStore } from 'redux';
import { BrowserRouter as Router, browserHistory } from 'react-router-dom';
import shortid from 'shortid';

import 'bootstrap/dist/css/bootstrap.css';
import 'font-awesome/css/font-awesome.css';

import '_resources/css/common.css';
import '_resources/css/non-responsive.css';
import '_resources/css/theme/cdc-bootstrap-theme.css';
import '_resources/css/theme/cdc-bootstrap-theme-extend.css';

import Layout from '_layouts/cdc';
import { view } from '_actions';
import reducers from '_reducers';
import { RouteWithSubRoutes } from '_components/router';

const store = createStore(reducers);

/**
 * 엔트리 포인트에서 사용되는 컨테이너
 * 모듈정보와 레이아웃 그리고 메뉴 자주 변하지 않는 데이터를 일괄적으로 로드한다.
 * 변경이 발생할 경우 푸쉬 방식으로 요청을 받아 새로 데이터를 수집한다.
 * redux 는 apps 에서만 사용한다.
 * @param {*} props
 */
class MainIndex extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      layoutHidden: false, // 레이아웃 숨김 여부
      browserTitle: '', // 브라우저 제목
      menus: {
        MENU0000000000000003: [
          {
            url: '/',
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000047',
            tree_id: 'j1_2',
            group_id: 'j1_2',
            parent_id: 'menu',
            parents_id: null,
            tree_name: '메일',
            tree_order: '1',
            url_type: 2,
            url_window: '_blank',
            url_pattern: null,
            tree_depth: 0,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 1,
            is_tree_menu: 0,
            is_hidden: 0,
            component: 'dashboard',
            strict: true,
            exact: true,
          },
          {
            url: '/2',
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000049',
            tree_id: 'j1_4',
            group_id: 'j1_4',
            parent_id: 'menu',
            parents_id: null,
            tree_name: '결재',
            tree_order: '2',
            url_type: 2,
            url_window: '_blank',
            url_pattern: null,
            tree_depth: 0,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 1,
            is_tree_menu: 0,
            is_hidden: 0,
            component: 'dashboard2',
            strict: false,
            exact: false,
          },
          {
            url: '/3',
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000075',
            tree_id: 'j1_1',
            group_id: 'j1_1',
            parent_id: 'menu',
            parents_id: null,
            tree_name: '문서함',
            tree_order: '3',
            url_type: 0,
            url_window: '_self',
            url_pattern: null,
            tree_depth: 0,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 0,
            is_tree_menu: 0,
            is_hidden: 0,
            component: 'demo',
            strict: false,
            exact: false,
          },
          {
            url: null,
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000050',
            tree_id: 'j1_5',
            group_id: 'j1_5',
            parent_id: 'menu',
            parents_id: null,
            tree_name: '게시판',
            tree_order: '4',
            url_type: 0,
            url_window: '_self',
            url_pattern: null,
            tree_depth: 0,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 1,
            is_tree_menu: 1,
            is_hidden: 0,
          },
          {
            url: '/board/latest',
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000088',
            tree_id: 'j1_23',
            group_id: 'j1_5',
            parent_id: 'j1_5',
            parents_id: 'j1_5',
            tree_name: '최근게시물',
            tree_order: '5',
            url_type: 0,
            url_window: '_self',
            url_pattern: '/board/**',
            tree_depth: 1,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 0,
            is_tree_menu: 0,
            is_hidden: 0,
          },
          {
            url: '/board/BOARDID00000001',
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000084',
            tree_id: 'j1_21',
            group_id: 'j1_5',
            parent_id: 'j1_5',
            parents_id: 'j1_5',
            tree_name: '공지사항',
            tree_order: '6',
            url_type: 0,
            url_window: '_self',
            url_pattern: '/board/BOARDID00000001/**',
            tree_depth: 1,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 0,
            is_tree_menu: 1,
            is_hidden: 0,
          },
          {
            url: '/board/BOARDID00000003',
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000086',
            tree_id: 'j1_20',
            group_id: 'j1_5',
            parent_id: 'j1_5',
            parents_id: 'j1_5',
            tree_name: '요청사항',
            tree_order: '7',
            url_type: 0,
            url_window: '_self',
            url_pattern: '/board/BOARDID00000003/**',
            tree_depth: 1,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 0,
            is_tree_menu: 0,
            is_hidden: 0,
          },
          {
            url: '/board/BOARDID00000004',
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000087',
            tree_id: 'j1_22',
            group_id: 'j1_5',
            parent_id: 'j1_5',
            parents_id: 'j1_5',
            tree_name: '경조사',
            tree_order: '8',
            url_type: 0,
            url_window: '_self',
            url_pattern: '/board/BOARDID00000004/**',
            tree_depth: 1,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 0,
            is_tree_menu: 0,
            is_hidden: 0,
          },
          {
            url: '/board/BOARDID00000002',
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000089',
            tree_id: 'j1_24',
            group_id: 'j1_5',
            parent_id: 'j1_5',
            parents_id: 'j1_5',
            tree_name: '이미지게시판',
            tree_order: '9',
            url_type: 0,
            url_window: '_self',
            url_pattern: '/board/BOARDID00000002/**',
            tree_depth: 1,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 0,
            is_tree_menu: 0,
            is_hidden: 0,
          },
          {
            url: "fnGWSSO('COP');",
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000055',
            tree_id: 'j1_6',
            group_id: 'j1_6',
            parent_id: 'menu',
            parents_id: null,
            tree_name: '동호회',
            tree_order: '10',
            url_type: 2,
            url_window: '_blank',
            url_pattern: null,
            tree_depth: 0,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 1,
            is_tree_menu: 0,
            is_hidden: 0,
          },
          {
            url: '/organization',
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000056',
            tree_id: 'j1_7',
            group_id: 'j1_7',
            parent_id: 'menu',
            parents_id: null,
            tree_name: '조직도',
            tree_order: '11',
            url_type: 0,
            url_window: '_self',
            url_pattern: '/organization/**',
            tree_depth: 0,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 1,
            is_tree_menu: 0,
            is_hidden: 0,
          },
          {
            url: '#',
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000057',
            tree_id: 'j1_8',
            group_id: 'j1_8',
            parent_id: 'menu',
            parents_id: null,
            tree_name: '통합업무',
            tree_order: '12',
            url_type: 1,
            url_window: '_blank',
            url_pattern: null,
            tree_depth: 0,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 1,
            is_tree_menu: 0,
            is_hidden: 0,
          },
          {
            url: null,
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000064',
            tree_id: 'j1_12',
            group_id: 'j1_12',
            parent_id: 'menu',
            parents_id: null,
            tree_name: '관리자',
            tree_order: '13',
            url_type: 0,
            url_window: '_self',
            url_pattern: null,
            tree_depth: 0,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 1,
            is_tree_menu: 0,
            is_hidden: 0,
          },
          {
            url: '/organization/manager/user',
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000065',
            tree_id: 'j1_17',
            group_id: 'j1_12',
            parent_id: 'j1_12',
            parents_id: 'j1_12',
            tree_name: '사용자관리',
            tree_order: '14',
            url_type: 0,
            url_window: '_self',
            url_pattern: '/organization/manager/user/**',
            tree_depth: 1,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 0,
            is_tree_menu: 0,
            is_hidden: 0,
          },
          {
            url: '/member/manager/config',
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000066',
            tree_id: 'j1_29',
            group_id: 'j1_12',
            parent_id: 'j1_12',
            parents_id: 'j1_12',
            tree_name: '로그인 설정',
            tree_order: '15',
            url_type: 0,
            url_window: '_self',
            url_pattern: '/member/manager/config/**',
            tree_depth: 1,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 0,
            is_tree_menu: 0,
            is_hidden: 0,
          },
          {
            url: '/menu/manager/tree/save/MENU0000000000000003',
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000067',
            tree_id: 'j1_18',
            group_id: 'j1_12',
            parent_id: 'j1_12',
            parents_id: 'j1_12',
            tree_name: '메뉴관리',
            tree_order: '16',
            url_type: 0,
            url_window: '_self',
            url_pattern: '/menu/manager/tree/save/**',
            tree_depth: 1,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 0,
            is_tree_menu: 0,
            is_hidden: 0,
          },
          {
            url: '/grant/manager/MENU0000000000000001',
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000068',
            tree_id: 'j1_19',
            group_id: 'j1_12',
            parent_id: 'j1_12',
            parents_id: 'j1_12',
            tree_name: '권한관리',
            tree_order: '17',
            url_type: 0,
            url_window: '_self',
            url_pattern: '/grant/manager/**',
            tree_depth: 1,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 0,
            is_tree_menu: 0,
            is_hidden: 0,
          },
          {
            url: '/board/manager',
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000070',
            tree_id: 'j1_13',
            group_id: 'j1_12',
            parent_id: 'j1_12',
            parents_id: 'j1_12',
            tree_name: '게시판관리',
            tree_order: '18',
            url_type: 0,
            url_window: '_self',
            url_pattern: '/board/manager/**',
            tree_depth: 1,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 0,
            is_tree_menu: 0,
            is_hidden: 0,
          },
          {
            url: '/popup/manager',
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000071',
            tree_id: 'j1_25',
            group_id: 'j1_12',
            parent_id: 'j1_12',
            parents_id: 'j1_12',
            tree_name: '팝업관리',
            tree_order: '19',
            url_type: 0,
            url_window: '_self',
            url_pattern: '/popup/manager/**',
            tree_depth: 1,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 0,
            is_tree_menu: 0,
            is_hidden: 0,
          },
          {
            url: '/sitelink/manager',
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000072',
            tree_id: 'j1_26',
            group_id: 'j1_12',
            parent_id: 'j1_12',
            parents_id: 'j1_12',
            tree_name: '사이트바로가기관리',
            tree_order: '20',
            url_type: 0,
            url_window: '_self',
            url_pattern: '/sitelink/manager/**',
            tree_depth: 1,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 0,
            is_tree_menu: 0,
            is_hidden: 0,
          },
          {
            url: '/occupancy/manager',
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000073',
            tree_id: 'j1_15',
            group_id: 'j1_12',
            parent_id: 'j1_12',
            parents_id: 'j1_12',
            tree_name: '재실등관리',
            tree_order: '21',
            url_type: 0,
            url_window: '_self',
            url_pattern: '/occupancy/manager/**',
            tree_depth: 1,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 0,
            is_tree_menu: 0,
            is_hidden: 0,
          },
          {
            url: '/promotionvideo/manager',
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000074',
            tree_id: 'j1_16',
            group_id: 'j1_12',
            parent_id: 'j1_12',
            parents_id: 'j1_12',
            tree_name: '홍보영상관리',
            tree_order: '22',
            url_type: 0,
            url_window: '_self',
            url_pattern: '/promotionvideo/manager/**',
            tree_depth: 1,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 0,
            is_tree_menu: 0,
            is_hidden: 0,
          },
          {
            url: null,
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000077',
            tree_id: 'j1_9',
            group_id: 'j1_12',
            parent_id: 'j1_12',
            parents_id: 'j1_12',
            tree_name: 'SMS관리',
            tree_order: '23',
            url_type: 0,
            url_window: '_self',
            url_pattern: null,
            tree_depth: 1,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 0,
            is_tree_menu: 0,
            is_hidden: 0,
          },
          {
            url: '/sms/manager/report',
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000078',
            tree_id: 'j1_10',
            group_id: 'j1_12',
            parent_id: 'j1_9',
            parents_id: 'j1_12,j1_9',
            tree_name: '발송현황',
            tree_order: '24',
            url_type: 0,
            url_window: '_self',
            url_pattern: '/sms/manager/report/**',
            tree_depth: 2,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 0,
            is_tree_menu: 0,
            is_hidden: 0,
          },
          {
            url: '/sms/manager/statistic',
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000079',
            tree_id: 'j1_11',
            group_id: 'j1_12',
            parent_id: 'j1_9',
            parents_id: 'j1_12,j1_9',
            tree_name: '통계',
            tree_order: '25',
            url_type: 0,
            url_window: '_self',
            url_pattern: '/sms/manager/statistic/**',
            tree_depth: 2,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 0,
            is_tree_menu: 0,
            is_hidden: 0,
          },
          {
            url: '/todaynotify/manager',
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000082',
            tree_id: 'j1_14',
            group_id: 'j1_12',
            parent_id: 'j1_12',
            parents_id: 'j1_12',
            tree_name: '오늘의 공지',
            tree_order: '26',
            url_type: 0,
            url_window: '_self',
            url_pattern: '/todaynotify/manager/**',
            tree_depth: 1,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 0,
            is_tree_menu: 0,
            is_hidden: 0,
          },
          {
            url: null,
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000062',
            tree_id: 'j1_27',
            group_id: 'j1_27',
            parent_id: 'menu',
            parents_id: null,
            tree_name: '개인정보설정',
            tree_order: '27',
            url_type: 0,
            url_window: '_self',
            url_pattern: null,
            tree_depth: 0,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 0,
            is_tree_menu: 0,
            is_hidden: 1,
          },
          {
            url: '/organization/user/password',
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000063',
            tree_id: 'j1_28',
            group_id: 'j1_27',
            parent_id: 'j1_27',
            parents_id: 'j1_27',
            tree_name: '비밀번호변경',
            tree_order: '28',
            url_type: 0,
            url_window: '_self',
            url_pattern: '/organization/user/password/**',
            tree_depth: 1,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 0,
            is_tree_menu: 0,
            is_hidden: 0,
          },
          {
            url: '/praisesticker',
            menu_idx: 'MENU0000000000000003',
            menu_tree_idx: 'MENUT000000000000076',
            tree_id: 'j1_3',
            group_id: 'j1_3',
            parent_id: 'menu',
            parents_id: null,
            tree_name: '칭찬스티커',
            tree_order: '29',
            url_type: 0,
            url_window: '_self',
            url_pattern: '/praisesticker/**',
            tree_depth: 0,
            image_basic: null,
            image_over: null,
            image_select: null,
            title_image: null,
            is_main_display: 0,
            is_tree_menu: 0,
            is_hidden: 0,
          },
        ],
      },
    };

    store.dispatch({
      type: view.SET_VIEW_INITIALIZE,
      data: this.state,
    });
  }

  render() {
    return (
      <Provider store={store}>
        <Router history={browserHistory}>
          <Layout>
            {this.state.menus.MENU0000000000000003.map((route) => {
              if (route.component !== undefined) {
                const pageId = shortid.generate();
                return (
                  <RouteWithSubRoutes
                    key={pageId}
                    {...route}
                  />
                );
              }
              return null;
            })}
          </Layout>
        </Router>
      </Provider>
    );
  }
}

export default MainIndex;
